### PR TITLE
This is a code for the HC-SR05 sensor.

### PR DESCRIPTION
**Pull request by The-Young-Programmer**

### CODE REVIEW

**Comment by Samuel-de-Oliveira** [comment]
That's right dude, also try to include all the libraries required in README tutorial (To HC-SR05 and HC-SR04).

And I want to place some videos to illustrate the project working, so I will record the HC-SR04 project first and can you record the HC-SR05 working?

**Comment by The-Young-Programmer** [comment]
Okay am still working on that, I was planing to include the library required into a new ReadMe inside the HC-SR05 folder.

The HC-SR05 and the HC-SR04 uses the same format just that the HC-SR05 has 5 pins while the HC-SR04 has 4 pins they work the same way .

**Comment by The-Young-Programmer** [comment]
@Samuel-de-Oliveira Hey buddy.

**Comment by Samuel-de-Oliveira** [comment]
I like what you made dude, but i noticed a thing

the project is for blind and **deaf blind** people and not for **deaf** XD

The deaf people actually can see, then they dont need this. Maybe this a fail in communication XD

But I really like how you organized the files, keep this.

**Comment by Samuel-de-Oliveira** [comment]
> Okay am still working on that, I was planing to include the library required into a new ReadMe inside the HC-SR05 folder.
> 
> The HC-SR05 and the HC-SR04 uses the same format just that the HC-SR05 has 5 pins while the HC-SR04 has 4 pins they work the same way .

Okay, I will only record HC-SR04 :+1:

**Comment by The-Young-Programmer** [comment]
> I like what you made dude, but i noticed a thing
> 
> the project is for blind and **deaf blind** people and not for **deaf** XD
> 
> The deaf people actually can see, then they dont need this. Maybe this a fail in communication XD
> 
> But I really like how you organized the files, keep this.

Thanks.
Oh you're right .

**Pull request merged**
