### PR TITLE
Update and rename Helen_Single_HC-SR04/Helen_Single_HC-SR04.ino to He…

### PR DESCRIPTION
**Pull request by The-Young-Programmer**
…len_Single_HC-SR05/Helen_Single_HC-SR05.ino

-  This tells us how far away the object is, measured in centimeters, then assigns that distance value to the cm variable.
- The next few lines will print the distance in centimeters to the serial monitor, which is helpful to make sure that the code is working properly and to see how far away your object is while you’re running the program.
- This code block will assign a frequency for the speaker to emit based on how far away the object is.

### CODE REVIEW

**Comment by The-Young-Programmer** [comment]
Hey there! I'm so glad you're here.

- **For the blind and deaf people**
I understand what you mean now, 
The blind will be able to hear sounds, but not see distances. 
The deaf will be able to see distances, but not hear sounds.

 - I'll keep the HC-SR04 version of this project, but if you want to make it cool, I have an idea in mind, check it out.
 
**Necessary components**
-  Arduino UNO
-  Ultrasonic sensor (HC-SR04)
-  Buzzer
- mini Speaker
- LCD Display

**NOTE**

The LCD display is for the deaf while the Buzzer and mini speaker is for the blind.

**Comment by The-Young-Programmer** [comment]
@Samuel-de-Oliveira How is it now, where you able to look into the code ?

**Comment by Samuel-de-Oliveira** [comment]
Hello, sorry to be late to respond.

And I`m having a idea now. So basically I want to create a directory with HC-SR04 sensor and HC-SR05 sensor. For while i don't have the HC-SR05 so I think you can help about it.

I will mage it, But you can create a new pull request to implement the HC-SR05 code.

**Comment by The-Young-Programmer** [comment]
Okay , sorry for late reply .
I will work on it and I will be using 

- Arduino UNO
- Ultrasonic sensor (HC-SR05)
- Buzzer
- mini Speaker
- LCD Display

**NOTE**
The LCD display is for the deaf while the Buzzer and mini speaker is for the blind

**Pull request merged**
